import type {
	Depot,
	EmergencyResource,
	Incident,
	ResourceDispatchLog,
	SafetyAlert,
	User,
	Volunteer,
	VolunteerTask,
	VolunteerTeam,
} from "#/types";

export const PREDEFINED_USERS: User[] = [
	{
		id: "usr-admin-1",
		name: "Brig. Gen. Tanvir Ahmed",
		email: "tanvir.ahmed@fscd.gov.bd",
		role: "admin",
		badgeTitle: "Director General (Operations) - FSCD",
		avatar:
			"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
		organization: "Fire Service and Civil Defence (FSCD) National Command",
		trustScore: 100,
		isVerified: true,
		phone: "+880 1711-002233",
		assignedJurisdiction:
			"National Disaster Emergency Operations Center (NDRCC)",
	},
	{
		id: "usr-resp-1",
		name: "Capt. Mahmudur Rahman",
		email: "mahmud.rahman@bdrcs.org",
		role: "responder",
		badgeTitle: "Water Rescue & USAR Lead",
		avatar:
			"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200",
		organization:
			"Bangladesh Red Crescent Society (BDRCS) Disaster Response Unit",
		trustScore: 98,
		isVerified: true,
		phone: "+880 1819-445566",
		assignedJurisdiction: "Chattogram & Coastal Response Sector",
	},
	{
		id: "usr-cit-verified-1",
		name: "Dr. Nusrat Jahan (MBBS)",
		email: "nusrat.jahan@sylhet-relief.org",
		role: "verified_citizen",
		badgeTitle: "Lead Medical Volunteer & Triage Specialist",
		avatar:
			"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
		organization: "Sylhet Haor Medical Relief Taskforce",
		trustScore: 94,
		isVerified: true,
		phone: "+880 1912-334455",
		assignedJurisdiction: "Surma Basin Emergency Medical Zone",
	},
	{
		id: "usr-cit-1",
		name: "Kazi Ashraful Islam",
		email: "ashraf.kazi@community.bd",
		role: "citizen",
		badgeTitle: "Local Community Volunteer / Reporter",
		avatar:
			"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200",
		organization: "Feni Flood Relief Action Group",
		trustScore: 82,
		isVerified: false,
		phone: "+880 1611-998877",
		assignedJurisdiction: "Feni Sadar & Fulgazi Sector",
	},
];

export const INITIAL_DEPOTS: Depot[] = [
	{
		id: "depot-1",
		name: "Dhaka Central Disaster Logistics Hub & Aviation Base",
		type: "central_hub",
		address: "Old Airport Road, Tejgaon, Dhaka-1215",
		lat: 23.7785,
		lng: 90.3842,
		capacity: 4000,
		currentOccupancy: 850,
		availableBeds: 1200,
		contactPhone: "+880 2-9555555",
		operatingStatus: "fully_operational",
		amenities: [
			"Helipad & Air Extraction",
			"Heavy De-watering Pumps",
			"Mobile Water Purification Units",
			"Vaccine & Cold Storage",
			"Inflatable Rescue Boat Fleet",
			"Satellite Comms Terminal",
		],
	},
	{
		id: "depot-2",
		name: "Sylhet MAG Osmani Medical College Emergency Trauma Center",
		type: "hospital",
		address: "Medical Road, Kajalshah, Sylhet Sadar, Sylhet-3100",
		lat: 24.8998,
		lng: 91.8546,
		capacity: 1500,
		currentOccupancy: 1380,
		availableBeds: 120,
		contactPhone: "+880 821-713667",
		operatingStatus: "strained",
		amenities: [
			"Emergency Cholera & Waterborne Disease Ward",
			"ICU Diesel Generator Backup",
			"Blood Bank & Saline Buffer",
			"Triage Ambulance Fleet",
			"Mobile Surgical Vans",
		],
	},
	{
		id: "depot-3",
		name: "Chattogram Naval & Coast Guard Emergency Staging Base",
		type: "field_station",
		address: "Port Access Road, Agrabad Commercial Area, Chattogram-4100",
		lat: 22.3275,
		lng: 91.8023,
		capacity: 1200,
		currentOccupancy: 420,
		availableBeds: 600,
		contactPhone: "+880 31-2510001",
		operatingStatus: "fully_operational",
		amenities: [
			"High-Speed Metal & Zodiac Rescue Boats",
			"Coastal Radar Weather Terminal",
			"Deep Diver Search Equipment",
			"Emergency Fuel Bunkers",
			"Life Jacket Reserves",
		],
	},
	{
		id: "depot-4",
		name: "Sunamganj Multi-Purpose Cyclone & Haor Flood Shelter",
		type: "shelter",
		address: "Tahirpur Highway, Sunamganj Sadar, Sunamganj-3000",
		lat: 25.0688,
		lng: 91.4022,
		capacity: 2200,
		currentOccupancy: 1980,
		availableBeds: 220,
		contactPhone: "+880 871-61234",
		operatingStatus: "strained",
		amenities: [
			"Elevated Multi-Tier Flood Refuge",
			"Solar-Powered Water Purification System",
			"Community Khichuri Kitchen",
			"Emergency Livestock Holding Platform",
			"Midwifery & First Aid Corner",
		],
	},
	{
		id: "depot-5",
		name: "Feni Pilot High School Emergency Evacuation Center",
		type: "shelter",
		address: "Grand Trunk Road, Feni Sadar, Feni-3900",
		lat: 23.0182,
		lng: 91.398,
		capacity: 1800,
		currentOccupancy: 1650,
		availableBeds: 150,
		contactPhone: "+880 331-74000",
		operatingStatus: "at_capacity",
		amenities: [
			"Emergency Classrooms Converted to Bunks",
			"High-Capacity Water Tanks",
			"Red Crescent Volunteer Field Camp",
			"Child Safe Play Space",
			"Emergency Battery Charging Station",
		],
	},
	{
		id: "depot-6",
		name: "Cox's Bazar Multi-Purpose Cyclone Shelter & CPP Base",
		type: "shelter",
		address: "Kolatoli Road, Marine Drive Junction, Cox's Bazar-4700",
		lat: 21.4285,
		lng: 91.979,
		capacity: 3500,
		currentOccupancy: 950,
		availableBeds: 2100,
		contactPhone: "+880 341-62200",
		operatingStatus: "fully_operational",
		amenities: [
			"Reinforced Category 5 Windproof Structure",
			"CPP Mega Siren Alert Tower",
			"Underground Rainwater Cistern (100,000L)",
			"Backup Solar Microgrid",
			"Emergency Radio Broadcast Mast",
		],
	},
	{
		id: "depot-7",
		name: "Kurigram Chilmari Jamuna Basin River Relief Depot",
		type: "field_station",
		address: "Chilmari Port Ghat Road, Chilmari, Kurigram-5630",
		lat: 25.5562,
		lng: 89.674,
		capacity: 1000,
		currentOccupancy: 380,
		availableBeds: 450,
		contactPhone: "+880 581-61100",
		operatingStatus: "fully_operational",
		amenities: [
			"Geotextile Sandbag Dump & Filling Cranes",
			"Country Engine Boat Fleet",
			"Tarpaulin Emergency Stockpile",
			"Mobile Purification Filtration Kits",
		],
	},
];

export const INITIAL_RESOURCES: EmergencyResource[] = [
	{
		id: "res-1",
		name: "Water Purification Tablets (Aquatabs / Halazone)",
		category: "medical",
		depotId: "depot-1",
		depotName: "Dhaka Central Disaster Logistics Hub",
		depotLocation: { lat: 23.7785, lng: 90.3842, address: "Tejgaon, Dhaka" },
		totalQuantity: 250000,
		allocatedQuantity: 160000,
		availableQuantity: 90000,
		unit: "strips (10pk)",
		minThreshold: 40000,
		status: "optimal",
		lastRestocked: "3 hours ago",
		contactOfficer: "Assistant Director Rafiqul Islam",
	},
	{
		id: "res-2",
		name: "Oral Rehydration Saline (ORS - 500ml Packets)",
		category: "medical",
		depotId: "depot-2",
		depotName: "Sylhet MAG Osmani Medical Center",
		depotLocation: { lat: 24.8998, lng: 91.8546, address: "Kajalshah, Sylhet" },
		totalQuantity: 50000,
		allocatedQuantity: 44000,
		availableQuantity: 6000,
		unit: "sachets",
		minThreshold: 10000,
		status: "critical_shortage",
		lastRestocked: "1 hour ago",
		contactOfficer: "Dr. Shahabuddin Ahmed",
	},
	{
		id: "res-3",
		name: "Inflatable Rescue Zodiac Speedboats & OBM 40HP",
		category: "vehicles",
		depotId: "depot-3",
		depotName: "Chattogram Naval & Coast Guard Base",
		depotLocation: {
			lat: 22.3275,
			lng: 91.8023,
			address: "Agrabad, Chattogram",
		},
		totalQuantity: 35,
		allocatedQuantity: 26,
		availableQuantity: 9,
		unit: "motorized boats",
		minThreshold: 10,
		status: "low_stock",
		lastRestocked: "6 hours ago",
		contactOfficer: "Lt. Cdr. Tariqul Anam",
	},
	{
		id: "res-4",
		name: "Dry Emergency Relief Food Packs (Chira, Gur, Biscuits)",
		category: "water_food",
		depotId: "depot-4",
		depotName: "Sunamganj Multi-Purpose Cyclone Shelter",
		depotLocation: {
			lat: 25.0688,
			lng: 91.4022,
			address: "Tahirpur Rd, Sunamganj",
		},
		totalQuantity: 15000,
		allocatedQuantity: 12200,
		availableQuantity: 2800,
		unit: "family ration packs",
		minThreshold: 3500,
		status: "low_stock",
		lastRestocked: "4 hours ago",
		contactOfficer: "Relief Officer Mozammel Haque",
	},
	{
		id: "res-5",
		name: "Heavy-Duty Diesel De-Watering Pumps (100 HP)",
		category: "power_fuel",
		depotId: "depot-1",
		depotName: "Dhaka Central Disaster Logistics Hub",
		depotLocation: { lat: 23.7785, lng: 90.3842, address: "Tejgaon, Dhaka" },
		totalQuantity: 60,
		allocatedQuantity: 42,
		availableQuantity: 18,
		unit: "pump units",
		minThreshold: 15,
		status: "optimal",
		lastRestocked: "12 hours ago",
		contactOfficer: "Engr. Masud Rana",
	},
	{
		id: "res-6",
		name: "Heavy Geotextile Embankment Sandbags (50kg)",
		category: "shelter_bedding",
		depotId: "depot-7",
		depotName: "Kurigram Chilmari River Relief Depot",
		depotLocation: {
			lat: 25.5562,
			lng: 89.674,
			address: "Chilmari Port, Kurigram",
		},
		totalQuantity: 80000,
		allocatedQuantity: 65000,
		availableQuantity: 15000,
		unit: "filled sandbags",
		minThreshold: 20000,
		status: "low_stock",
		lastRestocked: "5 hours ago",
		contactOfficer: "WDB Sub-Divisional Engineer Zahid",
	},
	{
		id: "res-7",
		name: "High-Frequency (HF/VHF) Emergency Mesh Radio Kits",
		category: "comms",
		depotId: "depot-6",
		depotName: "Cox's Bazar Multi-Purpose Cyclone Shelter",
		depotLocation: {
			lat: 21.4285,
			lng: 91.979,
			address: "Kolatoli, Cox's Bazar",
		},
		totalQuantity: 120,
		allocatedQuantity: 75,
		availableQuantity: 45,
		unit: "wireless units",
		minThreshold: 25,
		status: "optimal",
		lastRestocked: "8 hours ago",
		contactOfficer: "CPP Comms Officer Delwar",
	},
	{
		id: "res-8",
		name: "Waterproof Tarpaulins & Emergency Family Tents",
		category: "shelter_bedding",
		depotId: "depot-5",
		depotName: "Feni Pilot High School Evacuation Center",
		depotLocation: {
			lat: 23.0182,
			lng: 91.398,
			address: "Grand Trunk Rd, Feni",
		},
		totalQuantity: 8500,
		allocatedQuantity: 6900,
		availableQuantity: 1600,
		unit: "tents & tarps",
		minThreshold: 2000,
		status: "low_stock",
		lastRestocked: "2 hours ago",
		contactOfficer: "Volunteer Lead Kamrul Hasan",
	},
	{
		id: "res-9",
		name: "Mobile Solar Water Treatment & Desalination Units",
		category: "water_food",
		depotId: "depot-3",
		depotName: "Chattogram Naval & Coast Guard Base",
		depotLocation: {
			lat: 22.3275,
			lng: 91.8023,
			address: "Agrabad, Chattogram",
		},
		totalQuantity: 24,
		allocatedQuantity: 18,
		availableQuantity: 6,
		unit: "skid units",
		minThreshold: 5,
		status: "optimal",
		lastRestocked: "1 day ago",
		contactOfficer: "Lt. Aminur Rashid",
	},
];

export const INITIAL_INCIDENTS: Incident[] = [
	{
		id: "inc-bd-1",
		title: "Surma River Embankment Breach Submerging Villages",
		type: "flood",
		severity: "critical",
		status: "in_progress",
		description:
			"Catastrophic flash flood caused by massive upstream cloudburst runoff. The Surma river embankment breached at Tahirpur and Sunamganj Sadar, submerging over 45 villages under 6 to 9 feet of fast-flowing water. Thousands of families are stranded on rooftops and high school tin sheds with drinking water sources contaminated.",
		location: {
			lat: 25.0745,
			lng: 91.4055,
			address: "Tahirpur Upazila & Surma River Belt",
			city: "Sunamganj, Sylhet Division",
			landmark: "Near Tahirpur Haor Embankment Point 4",
		},
		reportedBy: {
			id: "usr-cit-verified-1",
			name: "Dr. Nusrat Jahan (MBBS)",
			role: "verified_citizen",
			isVerified: true,
			trustScore: 94,
			organization: "Sylhet Haor Medical Relief Taskforce",
		},
		createdAt: "25 mins ago",
		updatedAt: "10 mins ago",
		affectedCount: 68000,
		casualties: {
			injured: 42,
			missing: 11,
			fatalities: 2,
		},
		needs: [
			"Motorized Rescue Speedboats & Country Boats",
			"Water Purification Tablets (Aquatabs)",
			"Emergency IV Saline & Anti-Diarrheal Kits",
			"Dry Food Family Relief Packs (Chira, Gur)",
			"Solar Lighting & Mobile Charging Hubs",
		],
		corroborations: 84,
		corroboratedByUserIds: [
			"usr-admin-1",
			"usr-resp-1",
			"usr-cit-1",
			"vol-1",
			"vol-2",
		],
		assignedTeams: [
			"BDRCS Haor Water Rescue & Boat Squad",
			"Sylhet Emergency Medical Triage Corps",
		],
		allocatedResources: [
			{
				resourceId: "res-1",
				resourceName: "Water Purification Tablets (Aquatabs / Halazone)",
				quantity: 50000,
				unit: "strips (10pk)",
			},
			{
				resourceId: "res-4",
				resourceName: "Dry Emergency Relief Food Packs (Chira, Gur, Biscuits)",
				quantity: 3500,
				unit: "family ration packs",
			},
		],
		updates: [
			{
				id: "upd-101",
				authorName: "Dr. Nusrat Jahan",
				authorRole: "Lead Medical Volunteer",
				message:
					"Water levels rising rapidly along Tahirpur bazaar. We have mobilized 8 local country engine boats to ferry stranded children and elderly to the Sunamganj Multi-Purpose Cyclone Shelter.",
				timestamp: "20 mins ago",
				isOfficial: false,
			},
			{
				id: "upd-102",
				authorName: "Brig. Gen. Tanvir Ahmed",
				authorRole: "Director General (Operations) - FSCD",
				message:
					"FSCD Diving Teams and BDRCS Motorized Zodiacs dispatched from Sylhet base. 50,000 strips of Aquatabs and relief dry food allocated for immediate airdrop and boat distribution.",
				timestamp: "10 mins ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 12.0,
	},
	{
		id: "inc-bd-2",
		title: "Severe Cyclone Storm Surge & Coastal Inundation Threat",
		type: "hurricane",
		severity: "critical",
		status: "dispatched",
		description:
			"Severe Cyclonic Storm moving north-northeast towards Chattogram-Cox's Bazar coast with sustained winds of 145 km/h. Coastal tidal surge of 10 to 14 feet predicted during high tide. Low-lying unions of Sandwip, Mirsharai, and Anwara facing severe inundation. Over 45,000 residents being moved to concrete cyclone shelters.",
		location: {
			lat: 22.493,
			lng: 91.472,
			address: "Sandwip Coastal Embankment & Mirsharai Belt",
			city: "Chattogram Coast",
			landmark: "Sandwip Channel Western Embankment",
		},
		reportedBy: {
			id: "usr-resp-1",
			name: "Capt. Mahmudur Rahman",
			role: "responder",
			isVerified: true,
			trustScore: 98,
			organization:
				"Bangladesh Red Crescent Society (BDRCS) Disaster Response Unit",
		},
		createdAt: "1 hour ago",
		updatedAt: "15 mins ago",
		affectedCount: 120000,
		casualties: {
			injured: 18,
			missing: 4,
			fatalities: 0,
		},
		needs: [
			"High-Capacity Cyclone Shelters Intake",
			"CPP Mega Siren Alert Broadcasts",
			"Naval Speedboat Coastal Patrol",
			"Pre-positioned Dry Food Rations",
			"Heavy Concrete Shoring & Tree Clearing Gear",
		],
		corroborations: 112,
		corroboratedByUserIds: [
			"usr-admin-1",
			"usr-cit-verified-1",
			"vol-3",
			"vol-4",
		],
		assignedTeams: [
			"Cyclone Preparedness Programme (CPP) Coastal Rapid Taskforce",
		],
		allocatedResources: [
			{
				resourceId: "res-3",
				resourceName: "Inflatable Rescue Zodiac Speedboats & OBM 40HP",
				quantity: 12,
				unit: "motorized boats",
			},
			{
				resourceId: "res-7",
				resourceName: "High-Frequency (HF/VHF) Emergency Mesh Radio Kits",
				quantity: 30,
				unit: "wireless units",
			},
		],
		updates: [
			{
				id: "upd-201",
				authorName: "Capt. Mahmudur Rahman",
				authorRole: "Water Rescue Lead",
				message:
					"CPP volunteers sounding warning signal flag 8 across Sandwip. 18 coastal cyclone shelters activated and occupied up to 70% capacity.",
				timestamp: "45 mins ago",
				isOfficial: true,
			},
			{
				id: "upd-202",
				authorName: "Brig. Gen. Tanvir Ahmed",
				authorRole: "Director General - FSCD",
				message:
					"Navy and Coast Guard cutters stationed in outer anchorage. Power grid shut off preventatively in high-risk surge sectors.",
				timestamp: "15 mins ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 18.0,
	},
	{
		id: "inc-bd-3",
		title: "Muhuri & Gumti River Overflow Inundating Residential Sectors",
		type: "flood",
		severity: "high",
		status: "in_progress",
		description:
			"Continuous transboundary downpour has caused the Muhuri and Silonia rivers to breach protective dykes at 6 points across Fulgazi and Parshuram upazilas. Flood water has entered Feni Sadar ground floors, snapping electricity and submerging regional communication roads.",
		location: {
			lat: 23.132,
			lng: 91.428,
			address: "Fulgazi Upazila & Parshuram Highway",
			city: "Feni District, Chattogram Division",
			landmark: "Near Muhuri River Sluice Gate No. 2",
		},
		reportedBy: {
			id: "usr-cit-1",
			name: "Kazi Ashraful Islam",
			role: "citizen",
			isVerified: false,
			trustScore: 82,
			organization: "Feni Flood Relief Action Group",
		},
		createdAt: "2 hours ago",
		updatedAt: "35 mins ago",
		affectedCount: 35000,
		casualties: {
			injured: 14,
			missing: 3,
			fatalities: 1,
		},
		needs: [
			"Inflatable Rubber Boats & Lifebuoys",
			"Potable Bottled Drinking Water",
			"Waterproof Tarpaulins & Folding Cots",
			"Emergency Baby Formula & Dry Food",
		],
		corroborations: 67,
		corroboratedByUserIds: [
			"usr-resp-1",
			"usr-cit-verified-1",
			"vol-1",
			"vol-5",
		],
		assignedTeams: ["Feni Community Sandbagging & Flood Evac Patrol"],
		allocatedResources: [
			{
				resourceId: "res-8",
				resourceName: "Waterproof Tarpaulins & Emergency Family Tents",
				quantity: 2500,
				unit: "tents & tarps",
			},
			{
				resourceId: "res-1",
				resourceName: "Water Purification Tablets (Aquatabs / Halazone)",
				quantity: 30000,
				unit: "strips (10pk)",
			},
		],
		updates: [
			{
				id: "upd-301",
				authorName: "Kazi Ashraful Islam",
				authorRole: "Citizen Volunteer",
				message:
					"Water has reached waist level near Fulgazi pilot school. Over 300 families need boat extraction from isolated char homesteads.",
				timestamp: "1 hour ago",
				isOfficial: false,
			},
		],
		evacuationRadiusKm: 8.0,
	},
	{
		id: "inc-bd-4",
		title: "Catastrophic Jamuna River Bank Erosion Swallowing Farmland",
		type: "landslide",
		severity: "high",
		status: "investigating",
		description:
			"Severe swirling water vortexes in the receding Jamuna river have triggered massive bank erosion along Chilmari and Ulipur. Over 140 homesteads, an elementary school, and 200 meters of paved flood protection embankment have collapsed into the river within 24 hours.",
		location: {
			lat: 25.553,
			lng: 89.671,
			address: "Chilmari Port Ghat & River Embankment",
			city: "Kurigram, Rangpur Division",
			landmark: "Chilmari Old Steamer Ghat",
		},
		reportedBy: {
			id: "usr-admin-1",
			name: "Brig. Gen. Tanvir Ahmed",
			role: "admin",
			isVerified: true,
			trustScore: 100,
			organization: "FSCD National Command",
		},
		createdAt: "3 hours ago",
		updatedAt: "1 hour ago",
		affectedCount: 14000,
		casualties: {
			injured: 6,
			missing: 1,
			fatalities: 0,
		},
		needs: [
			"Geotextile Sandbag Dumping Trucks",
			"Emergency Relocation Land & Tents",
			"Country Cargo Boats for Household Salvage",
			"Drinking Water Tube Wells (Disinfected)",
		],
		corroborations: 43,
		corroboratedByUserIds: ["usr-resp-1", "vol-6"],
		assignedTeams: ["Dhaka Urban Heavy Search & First Aid Brigade"],
		allocatedResources: [
			{
				resourceId: "res-6",
				resourceName: "Heavy Geotextile Embankment Sandbags (50kg)",
				quantity: 20000,
				unit: "filled sandbags",
			},
		],
		updates: [
			{
				id: "upd-401",
				authorName: "Water Development Board Team",
				authorRole: "Embankment Engineers",
				message:
					"Dumping 20,000 geo-bags along critical erosion spur. Families being shifted 1.5 km inland to high school grounds.",
				timestamp: "1 hour ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 5.0,
	},
	{
		id: "inc-bd-5",
		title: "Urban Waterlogging & 33kV Substation Short-Circuit Hazard",
		type: "power_outage",
		severity: "moderate",
		status: "in_progress",
		description:
			"Heavy monsoon cloudburst dumped 140mm rainfall in 3 hours, overwhelming Dhaka stormwater drainage. Waist-deep waterlogging in Mirpur-10, Kazipara, and Shewrapara has inundated an electrical substation, posing critical electrocution risk and knocking out power to 80,000 households.",
		location: {
			lat: 23.807,
			lng: 90.3685,
			address: "Mirpur-10 Roundabout & Kazipara Main Road",
			city: "Dhaka North City Corporation",
			landmark: "Near Mirpur-10 Metro Rail Station Pillar 182",
		},
		reportedBy: {
			id: "usr-resp-1",
			name: "Capt. Mahmudur Rahman",
			role: "responder",
			isVerified: true,
			trustScore: 98,
			organization: "FSCD Urban Rescue Division",
		},
		createdAt: "4 hours ago",
		updatedAt: "45 mins ago",
		affectedCount: 85000,
		casualties: {
			injured: 3,
			missing: 0,
			fatalities: 0,
		},
		needs: [
			"High-Capacity Diesel De-Watering Pumps",
			"DESCO Rapid Electrical Isolation Crews",
			"Rubber Inflatable Dinghies for Commuter Transfer",
		],
		corroborations: 95,
		corroboratedByUserIds: [
			"usr-admin-1",
			"usr-cit-1",
			"vol-1",
			"vol-2",
			"vol-3",
		],
		assignedTeams: ["Dhaka Urban Heavy Search & First Aid Brigade"],
		allocatedResources: [
			{
				resourceId: "res-5",
				resourceName: "Heavy-Duty Diesel De-Watering Pumps (100 HP)",
				quantity: 8,
				unit: "pump units",
			},
		],
		updates: [
			{
				id: "upd-501",
				authorName: "FSCD Mirpur Station",
				authorRole: "Station Officer",
				message:
					"8 high-capacity de-watering pumps operating continuously. Water pumped out into Kallyanpur canal. Electrical feeder safely isolated.",
				timestamp: "45 mins ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 2.0,
	},
	{
		id: "inc-bd-6",
		title: "Monsoon Hillside Landslide Threatening Foothill Slums",
		type: "landslide",
		severity: "high",
		status: "contained",
		description:
			"Continuous torrential rains triggered a major mudslide on Batali Hill and Lalkhan Bazar hillside. 18 semi-pucca houses damaged at the base. Responders evacuated 65 families just prior to major debris slide.",
		location: {
			lat: 22.348,
			lng: 91.821,
			address: "Batali Hill Foothills & Lalkhan Bazar",
			city: "Chattogram Metropolitan",
			landmark: "Tigerpass Junction Foothill Slope",
		},
		reportedBy: {
			id: "usr-resp-1",
			name: "Capt. Mahmudur Rahman",
			role: "responder",
			isVerified: true,
			trustScore: 98,
			organization: "BDRCS Chattogram Unit",
		},
		createdAt: "6 hours ago",
		updatedAt: "2 hours ago",
		affectedCount: 1200,
		casualties: {
			injured: 8,
			missing: 0,
			fatalities: 0,
		},
		needs: [
			"Heavy Earthmover Excavators",
			"Structural Shoring Props & Jacking Gear",
			"Temporary Evacuation Shelter Space",
		],
		corroborations: 51,
		corroboratedByUserIds: ["usr-admin-1", "usr-cit-verified-1", "vol-4"],
		assignedTeams: [
			"Cyclone Preparedness Programme (CPP) Coastal Rapid Taskforce",
		],
		allocatedResources: [],
		updates: [
			{
				id: "upd-601",
				authorName: "Chattogram City Corporation Disaster Cell",
				authorRole: "Civil Defence Magistrate",
				message:
					"Perimeter cordoned off. 65 families relocated to Tigerpass Government Primary School Shelter.",
				timestamp: "2 hours ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 1.5,
	},
	{
		id: "inc-bd-7",
		title: "Chemical Warehouse Storage Fire & Toxic Fume Cloud",
		type: "hazmat",
		severity: "critical",
		status: "contained",
		description:
			"Industrial solvent storage facility fire producing thick acrid toxic fumes containing sulfuric and benzene vapors. 12 FSCD fire engines deployed with chemical foam tenders. Surrounding residential colonies evacuated.",
		location: {
			lat: 23.765,
			lng: 90.399,
			address: "Tejgaon Industrial Area, Shahid Tajuddin Ahmed Sarani",
			city: "Dhaka Metropolitan",
			landmark: "Near Tejgaon Rail Gate & Channel i Road",
		},
		reportedBy: {
			id: "usr-admin-1",
			name: "Brig. Gen. Tanvir Ahmed",
			role: "admin",
			isVerified: true,
			trustScore: 100,
			organization: "FSCD National Command",
		},
		createdAt: "8 hours ago",
		updatedAt: "3 hours ago",
		affectedCount: 8500,
		casualties: {
			injured: 12,
			missing: 0,
			fatalities: 0,
		},
		needs: [
			"Chemical Resistant Hazmat Suits (Level A/B)",
			"AFFF High-Expansion Foam Concentrate",
			"Air Quality Atmospheric Monitoring Sensors",
		],
		corroborations: 76,
		corroboratedByUserIds: ["usr-resp-1", "usr-cit-1", "vol-1"],
		assignedTeams: ["Dhaka Urban Heavy Search & First Aid Brigade"],
		allocatedResources: [],
		updates: [
			{
				id: "upd-701",
				authorName: "FSCD Hazmat Specialist",
				authorRole: "Hazmat Incident Commander",
				message:
					"Fire fully contained using dry chemical powder and AFFF foam. Air scrubbers active. Residual gas dispersal underway.",
				timestamp: "3 hours ago",
				isOfficial: true,
			},
		],
		evacuationRadiusKm: 2.5,
	},
];

export const INITIAL_SAFETY_ALERTS: SafetyAlert[] = [
	{
		id: "alert-bd-1",
		title: "CYCLONE DANGER WARNING SIGNAL 10: Coastal Belt",
		severity: "extreme",
		disasterType: "hurricane",
		headline:
			"Very Severe Cyclonic Storm Approaching Chattogram & Cox's Bazar Coasts",
		instructions: [
			"Immediate mandatory evacuation of all residents in Sandwip, Mirsharai, Anwara, Kutubdia, and Maheshkhali.",
			"Seek concrete shelter in multi-purpose cyclone shelters or designated pucca school buildings before high tide.",
			"Secure drinking water canisters, dry food, and essential medications in waterproof plastic wrapping.",
			"Do not venture out into the sea or river channels; all fishing trawlers and cargo vessels must remain anchored.",
			"Emergency Hotline: Dial 1090 (Toll-Free BMD Warning) or 999 (National Emergency).",
		],
		affectedAreas: [
			"Chattogram Coastal Belt (Sandwip, Mirsharai, Sitakunda, Anwara)",
			"Cox's Bazar (Kutubdia, Maheshkhali, Teknaf, Saint Martin)",
			"Noakhali & Hatiya Island",
			"Bhola Coastal Char Zones",
		],
		zones: [
			{
				id: "zone-bd-1",
				name: "Sandwip & Coastal Surge Mandatory Evacuation Zone",
				lat: 22.493,
				lng: 91.472,
				radiusKm: 16.0,
				level: "mandatory_evacuation",
				color: "#dc2626",
				description:
					"High risk of 10-14ft tidal surge inundating coastal dykes. Full evacuation mandatory.",
			},
			{
				id: "zone-bd-2",
				name: "Chattogram Metropolitan & Agrabad High Alert Zone",
				lat: 22.3275,
				lng: 91.8023,
				radiusKm: 12.0,
				level: "prepare_to_evacuate",
				color: "#ea580c",
				description:
					"Heavy gales (110 km/h) and urban waterlogging alert. Secure loose rooftops and generators.",
			},
			{
				id: "zone-bd-3",
				name: "Cox's Bazar Cyclone Shelter Refuge Corridor",
				lat: 21.4285,
				lng: 91.979,
				radiusKm: 8.0,
				level: "safe_corridor",
				color: "#10b981",
				description:
					"Reinforced cyclone shelters operational with backup solar water filtration and medical cots.",
			},
		],
		broadcastAt: "1 hour ago",
		expiresAt: "In 18 hours",
		active: true,
		broadcastedBy: "Bangladesh Meteorological Department (BMD) & NDRCC",
	},
	{
		id: "alert-bd-2",
		title: "FLASH FLOOD EMERGENCY BULLETIN: Surma-Kushiyara Basin",
		severity: "severe",
		disasterType: "flood",
		headline: "Surma & Kushiyara Rivers Flowing 1.8m Above Severe Danger Level",
		instructions: [
			"Residents in Tahirpur, Sunamganj Sadar, Bishwamvarpur, and Companiganj must move to elevated flood shelters.",
			"Boil all water before drinking or use Aquatabs water purification tablets; avoid drinking flood runoff.",
			"Keep oral rehydration saline (ORS) packets ready for infants and elderly.",
			"Report stranded families to local UP Disaster Management Committees or BDRCS boat squads.",
		],
		affectedAreas: [
			"Sunamganj District (All 12 Upazilas)",
			"Sylhet Sadar, Companiganj, Gowainghat, Kanaighat",
			"Netrokona Haor Basin",
			"Habiganj Low-Lying Unions",
		],
		zones: [
			{
				id: "zone-bd-4",
				name: "Sunamganj Haor Basin Catastrophic Inundation Area",
				lat: 25.0745,
				lng: 91.4055,
				radiusKm: 20.0,
				level: "mandatory_evacuation",
				color: "#dc2626",
				description:
					"Surma river breached dykes. Deep water cover over roadway networks. Boat evacuation only.",
			},
			{
				id: "zone-bd-5",
				name: "Sylhet Osmani Medical Safe Treatment Corridor",
				lat: 24.8998,
				lng: 91.8546,
				radiusKm: 6.0,
				level: "safe_corridor",
				color: "#10b981",
				description:
					"Emergency trauma hospital with high-capacity diesel generators and waterborne disease wards.",
			},
		],
		broadcastAt: "3 hours ago",
		expiresAt: "In 24 hours",
		active: true,
		broadcastedBy: "Flood Forecasting and Warning Centre (FFWC) - BWDB",
	},
	{
		id: "alert-bd-3",
		title: "URBAN WATERLOGGING & ELECTROCUTION ADVISORY: Greater Dhaka",
		severity: "moderate",
		disasterType: "power_outage",
		headline:
			"Extreme Rainfall Causing Deep Arterial Waterlogging across Dhaka North",
		instructions: [
			"Avoid wading through submerged streets near electrical transformers, fallen wires, and lampposts.",
			"Use designated metro rail corridors or elevated flyovers; avoid low-lying underpasses.",
			"Contact DESCO / DPDC emergency helplines before touching inundated building meter panels.",
		],
		affectedAreas: [
			"Mirpur 1, 2, 10, 11, Kazipara, Shewrapara",
			"Kallyanpur, Shyamoli, Mohammadpur",
			"Jurain, Shyampur, DND Canal Embankment",
		],
		zones: [
			{
				id: "zone-bd-6",
				name: "Mirpur Electrical Substation Hazard Zone",
				lat: 23.807,
				lng: 90.3685,
				radiusKm: 3.5,
				level: "shelter_in_place",
				color: "#eab308",
				description:
					"33kV substation isolation in progress. Water pumps active. Pedestrians avoid standing water.",
			},
		],
		broadcastAt: "4 hours ago",
		expiresAt: "In 6 hours",
		active: true,
		broadcastedBy: "Dhaka North City Corporation (DNCC) Emergency Cell",
	},
];

export const INITIAL_DISPATCH_LOGS: ResourceDispatchLog[] = [
	{
		id: "disp-101",
		incidentId: "inc-bd-1",
		incidentTitle: "Surma River Embankment Breach Submerging Villages",
		fromDepotId: "depot-1",
		fromDepotName: "Dhaka Central Disaster Logistics Hub",
		items: [
			{
				resourceName: "Water Purification Tablets (Aquatabs / Halazone)",
				quantity: 50000,
				unit: "strips (10pk)",
			},
		],
		dispatchedAt: "20 mins ago",
		eta: "Arrived on Site",
		status: "delivered",
		dispatchedBy: "Brig. Gen. Tanvir Ahmed",
		notes:
			"Airdropped and distributed via BDRCS motorboats to Tahirpur Haor evacuees.",
	},
	{
		id: "disp-102",
		incidentId: "inc-bd-1",
		incidentTitle: "Surma River Embankment Breach Submerging Villages",
		fromDepotId: "depot-4",
		fromDepotName: "Sunamganj Multi-Purpose Cyclone Shelter",
		items: [
			{
				resourceName: "Dry Emergency Relief Food Packs (Chira, Gur, Biscuits)",
				quantity: 3500,
				unit: "family ration packs",
			},
		],
		dispatchedAt: "15 mins ago",
		eta: "10 mins",
		status: "in_transit",
		dispatchedBy: "Relief Officer Mozammel Haque",
		notes:
			"Transported via shallow engine country boats to marooned rooftop families.",
	},
	{
		id: "disp-103",
		incidentId: "inc-bd-2",
		incidentTitle: "Severe Cyclone Storm Surge & Coastal Inundation Threat",
		fromDepotId: "depot-3",
		fromDepotName: "Chattogram Naval & Coast Guard Base",
		items: [
			{
				resourceName: "Inflatable Rescue Zodiac Speedboats & OBM 40HP",
				quantity: 12,
				unit: "motorized boats",
			},
		],
		dispatchedAt: "45 mins ago",
		eta: "Arrived at Sandwip Ghat",
		status: "delivered",
		dispatchedBy: "Capt. Mahmudur Rahman",
		notes:
			"Positioned along Sandwip western channel for high tide rescue operations.",
	},
	{
		id: "disp-104",
		incidentId: "inc-bd-5",
		incidentTitle: "Urban Waterlogging & 33kV Substation Short-Circuit Hazard",
		fromDepotId: "depot-1",
		fromDepotName: "Dhaka Central Disaster Logistics Hub",
		items: [
			{
				resourceName: "Heavy-Duty Diesel De-Watering Pumps (100 HP)",
				quantity: 8,
				unit: "pump units",
			},
		],
		dispatchedAt: "2 hours ago",
		eta: "Operational",
		status: "delivered",
		dispatchedBy: "Engr. Masud Rana",
		notes: "Installed and discharging into Kallyanpur storm drainage canal.",
	},
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
	{
		id: "vol-1",
		name: "Kazi Ashraful Islam",
		email: "ashraf.kazi@community.bd",
		phone: "+880 1611-998877",
		avatar:
			"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
		skills: [
			"evac_transport",
			"search_rescue",
			"food_water_dist",
			"shelter_management",
		],
		status: "deployed",
		teamId: "team-3",
		teamName: "Feni Community Sandbagging & Flood Evac Patrol",
		certifications: [
			"BDRCS Community Disaster Management",
			"First Aid Certified",
		],
		experienceHours: 180,
		joinedDate: "3 years ago",
		location: {
			address: "Grand Trunk Road, Feni Sadar",
			city: "Feni",
			lat: 23.0182,
			lng: 91.398,
		},
		emergencyContact: "Kazi Nurul Islam (+880 1819-223344)",
		currentTaskTitle: "Sandbagging Muhuri River Dyke in Fulgazi",
	},
	{
		id: "vol-2",
		name: "Dr. Nusrat Jahan (MBBS)",
		email: "nusrat.jahan@sylhet-relief.org",
		phone: "+880 1912-334455",
		avatar:
			"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
		skills: ["first_aid_cpr", "psych_first_aid", "food_water_dist"],
		status: "deployed",
		teamId: "team-2",
		teamName: "Sylhet Emergency Medical Triage Corps",
		certifications: [
			"MBBS (Osmani Medical College)",
			"WHO Mass Casualty Management",
		],
		experienceHours: 420,
		joinedDate: "4 years ago",
		location: {
			address: "Medical Road, Kajalshah, Sylhet",
			city: "Sylhet",
			lat: 24.8998,
			lng: 91.8546,
		},
		emergencyContact: "Dr. Mahfuzur Rahman (+880 1711-889900)",
		currentTaskTitle: "Waterborne Disease Screening & IV Saline Distribution",
	},
	{
		id: "vol-3",
		name: "Tanvir Hasan",
		email: "tanvir.hasan@cpp-bd.org",
		phone: "+880 1815-112233",
		avatar:
			"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
		skills: ["search_rescue", "comms_radio", "drone_recon", "evac_transport"],
		status: "deployed",
		teamId: "team-1",
		teamName: "Cyclone Preparedness Programme (CPP) Coastal Taskforce",
		certifications: ["CPP Master Volunteer Badge #402", "VHF Radio Operator"],
		experienceHours: 510,
		joinedDate: "5 years ago",
		location: {
			address: "Sandwip Sadar Ghat, Chattogram",
			city: "Chattogram",
			lat: 22.493,
			lng: 91.472,
		},
		emergencyContact: "Hasanuzzaman (+880 1819-556677)",
		currentTaskTitle: "Signal Flag Broadcast & Coastal Char Evacuation",
	},
	{
		id: "vol-4",
		name: "Farhana Yasmin",
		email: "farhana.yasmin@bdrcs.org",
		phone: "+880 1712-445566",
		avatar:
			"https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
		skills: [
			"shelter_management",
			"food_water_dist",
			"psych_first_aid",
			"bilingual_translation",
		],
		status: "deployed",
		teamId: "team-1",
		teamName: "Cyclone Preparedness Programme (CPP) Coastal Taskforce",
		certifications: [
			"Red Crescent Youth Leader",
			"Child Protection in Emergencies",
		],
		experienceHours: 290,
		joinedDate: "2 years ago",
		location: {
			address: "Agrabad, Chattogram",
			city: "Chattogram",
			lat: 22.3275,
			lng: 91.8023,
		},
		emergencyContact: "Yasmin Begum (+880 1711-667788)",
		currentTaskTitle: "Cyclone Shelter Intake & Hot Meal Logistics",
	},
	{
		id: "vol-5",
		name: "Shamim Reza",
		email: "shamim.reza@haor-rescue.bd",
		phone: "+880 1718-990011",
		avatar:
			"https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
		skills: ["search_rescue", "evac_transport", "first_aid_cpr"],
		status: "deployed",
		teamId: "team-4",
		teamName: "BDRCS Haor Water Rescue & Boat Squad",
		certifications: ["Inland Waterway Rescue Pilot", "Basic Life Support"],
		experienceHours: 340,
		joinedDate: "3 years ago",
		location: {
			address: "Tahirpur, Sunamganj",
			city: "Sunamganj",
			lat: 25.0745,
			lng: 91.4055,
		},
		emergencyContact: "Rezaul Karim (+880 1715-334455)",
		currentTaskTitle: "Haor Motorboat Evacuation Operations",
	},
	{
		id: "vol-6",
		name: "Arif Hossain",
		email: "arif.hossain@fscd-vol.gov.bd",
		phone: "+880 1812-778899",
		avatar:
			"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
		skills: ["search_rescue", "heavy_machinery", "first_aid_cpr"],
		status: "ready",
		teamId: "team-5",
		teamName: "Dhaka Urban Heavy Search & First Aid Brigade",
		certifications: [
			"FSCD Certified Community Rescuer",
			"Heavy Equipment Operator",
		],
		experienceHours: 210,
		joinedDate: "2 years ago",
		location: {
			address: "Mirpur-10, Dhaka",
			city: "Dhaka",
			lat: 23.807,
			lng: 90.3685,
		},
		emergencyContact: "Mofizur Rahman (+880 1811-223344)",
	},
	{
		id: "vol-7",
		name: "Tasnim Akter",
		email: "tasnim.akter@community.bd",
		phone: "+880 1914-556677",
		avatar:
			"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
		skills: ["food_water_dist", "first_aid_cpr", "shelter_management"],
		status: "ready",
		certifications: ["Community First Responder"],
		experienceHours: 95,
		joinedDate: "1 year ago",
		location: {
			address: "Tejgaon, Dhaka",
			city: "Dhaka",
			lat: 23.7785,
			lng: 90.3842,
		},
		emergencyContact: "Akhtar Hossain (+880 1911-334455)",
	},
	{
		id: "vol-8",
		name: "Zubair Ahmed",
		email: "zubair.ahmed@drone-bd.org",
		phone: "+880 1618-223344",
		avatar:
			"https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
		skills: ["drone_recon", "comms_radio"],
		status: "ready",
		certifications: [
			"Civil Aviation Drone Pilot License",
			"Ham Radio License S21BD",
		],
		experienceHours: 150,
		joinedDate: "1 year ago",
		location: {
			address: "Uttara Sector 7, Dhaka",
			city: "Dhaka",
			lat: 23.868,
			lng: 90.398,
		},
		emergencyContact: "Jamil Ahmed (+880 1611-778899)",
	},
];

export const INITIAL_VOLUNTEER_TEAMS: VolunteerTeam[] = [
	{
		id: "team-1",
		name: "Cyclone Preparedness Programme (CPP) Coastal Taskforce",
		callsign: "COASTAL-SENTINEL-1",
		specialty: "search_rescue",
		leaderId: "usr-resp-1",
		leaderName: "Capt. Mahmudur Rahman",
		memberIds: ["vol-3", "vol-4"],
		maxCapacity: 12,
		status: "active_mission",
		assignedIncidentId: "inc-bd-2",
		assignedIncidentTitle:
			"Severe Cyclone Storm Surge & Coastal Inundation Threat",
		stagingDepotId: "depot-3",
		stagingDepotName: "Chattogram Naval & Coast Guard Base",
		activeTaskId: "task-bd-1",
		activeTaskTitle: "Sandwip Coastal Embankment Evacuation Patrol",
		createdAt: "3 days ago",
		notes:
			"Operating across Sandwip, Mirsharai, and Anwara coastal surge corridors.",
	},
	{
		id: "team-2",
		name: "Sylhet Emergency Medical Triage Corps",
		callsign: "HAOR-MEDIC-ALPHA",
		specialty: "medical_triage",
		leaderId: "usr-cit-verified-1",
		leaderName: "Dr. Nusrat Jahan (MBBS)",
		memberIds: ["vol-2"],
		maxCapacity: 8,
		status: "active_mission",
		assignedIncidentId: "inc-bd-1",
		assignedIncidentTitle: "Surma River Embankment Breach Submerging Villages",
		stagingDepotId: "depot-2",
		stagingDepotName: "Sylhet MAG Osmani Medical Center",
		activeTaskId: "task-bd-2",
		activeTaskTitle:
			"Waterborne Disease Screening & IV Saline Camp in Tahirpur",
		createdAt: "2 days ago",
		notes:
			"Equipped with cholera treatment cots, oral saline, and water testing kits.",
	},
	{
		id: "team-3",
		name: "Feni Community Sandbagging & Flood Evac Patrol",
		callsign: "FENI-DELTA-RESCUE",
		specialty: "flood_sandbagging",
		leaderId: "usr-cit-1",
		leaderName: "Kazi Ashraful Islam",
		memberIds: ["vol-1"],
		maxCapacity: 10,
		status: "active_mission",
		assignedIncidentId: "inc-bd-3",
		assignedIncidentTitle:
			"Muhuri & Gumti River Overflow Inundating Residential Sectors",
		stagingDepotId: "depot-5",
		stagingDepotName: "Feni Pilot High School Evacuation Center",
		activeTaskId: "task-bd-3",
		activeTaskTitle: "Emergency Sandbag Reinforcement at Fulgazi Sluice Gate",
		createdAt: "1 day ago",
		notes:
			"Local youths mobilized with rubber dinghies and sandbag transport tractors.",
	},
	{
		id: "team-4",
		name: "BDRCS Haor Water Rescue & Boat Squad",
		callsign: "SURMA-WATER-WING",
		specialty: "evacuation_logistics",
		leaderId: "vol-5",
		leaderName: "Shamim Reza",
		memberIds: ["vol-5"],
		maxCapacity: 8,
		status: "active_mission",
		assignedIncidentId: "inc-bd-1",
		assignedIncidentTitle: "Surma River Embankment Breach Submerging Villages",
		stagingDepotId: "depot-4",
		stagingDepotName: "Sunamganj Multi-Purpose Cyclone Shelter",
		activeTaskId: "task-bd-4",
		activeTaskTitle: "Marooned Family Boat Extraction in Sunamganj Haor",
		createdAt: "2 days ago",
		notes: "Operating 6 motorized shallow-draft country rescue boats.",
	},
	{
		id: "team-5",
		name: "Dhaka Urban Heavy Search & First Aid Brigade",
		callsign: "DHAKA-URBAN-USAR",
		specialty: "general_response",
		leaderId: "usr-admin-1",
		leaderName: "Brig. Gen. Tanvir Ahmed",
		memberIds: ["vol-6"],
		maxCapacity: 15,
		status: "standby",
		assignedIncidentId: "inc-bd-5",
		assignedIncidentTitle:
			"Urban Waterlogging & 33kV Substation Short-Circuit Hazard",
		stagingDepotId: "depot-1",
		stagingDepotName: "Dhaka Central Disaster Logistics Hub",
		createdAt: "5 days ago",
		notes:
			"Rapid mobilization unit with concrete cutters, de-watering pumps, and thermal drones.",
	},
];

export const INITIAL_VOLUNTEER_TASKS: VolunteerTask[] = [
	{
		id: "task-bd-1",
		title: "Sandwip Coastal Embankment Evacuation Patrol",
		description:
			"Sound warning siren flags, assist elderly and pregnant women onto high-chassis evacuation tractors, and ensure shelter transfer before high tide surge.",
		category: "search_rescue",
		priority: "critical",
		status: "in_progress",
		incidentId: "inc-bd-2",
		incidentTitle: "Severe Cyclone Storm Surge & Coastal Inundation Threat",
		assignedTeamId: "team-1",
		assignedTeamName: "Cyclone Preparedness Programme (CPP) Coastal Taskforce",
		assignedVolunteerIds: ["vol-3", "vol-4"],
		location: {
			address: "Sandwip Western Embankment, Chattogram",
			lat: 22.493,
			lng: 91.472,
		},
		requiredSkills: ["search_rescue", "evac_transport", "comms_radio"],
		volunteersNeeded: 6,
		estimatedDurationHours: 6,
		deadline: "Before 17:00 High Tide",
		createdBy: "Capt. Mahmudur Rahman (BDRCS Lead)",
		createdAt: "2 hours ago",
		checkIns: [
			{
				id: "chk-1",
				volunteerId: "vol-3",
				volunteerName: "Tanvir Hasan",
				timestamp: "1 hour ago",
				note: "Evacuated 85 families from char villages to Sandwip Multi-Purpose Shelter #3. Signal flag 8 hoisted.",
			},
			{
				id: "chk-2",
				volunteerId: "vol-4",
				volunteerName: "Farhana Yasmin",
				timestamp: "30 mins ago",
				note: "Shelter registration complete for 450 individuals. Hot khichuri cooking in progress.",
			},
		],
		safetyNotes:
			"Wear life jackets at all times. Watch for snapped electrical wires.",
	},
	{
		id: "task-bd-2",
		title: "Waterborne Disease Screening & IV Saline Camp in Tahirpur",
		description:
			"Set up mobile oral rehydration stations, screen flood victims for acute watery diarrhea, and distribute Aquatabs water purification strips.",
		category: "medical_aid",
		priority: "critical",
		status: "in_progress",
		incidentId: "inc-bd-1",
		incidentTitle: "Surma River Embankment Breach Submerging Villages",
		assignedTeamId: "team-2",
		assignedTeamName: "Sylhet Emergency Medical Triage Corps",
		assignedVolunteerIds: ["vol-2"],
		location: {
			address: "Tahirpur Upazila Health Complex Yard, Sunamganj",
			lat: 25.0745,
			lng: 91.4055,
		},
		requiredSkills: ["first_aid_cpr", "psych_first_aid"],
		volunteersNeeded: 4,
		estimatedDurationHours: 8,
		deadline: "Today by 19:00",
		createdBy: "Dr. Nusrat Jahan (MBBS)",
		createdAt: "3 hours ago",
		checkIns: [
			{
				id: "chk-3",
				volunteerId: "vol-2",
				volunteerName: "Dr. Nusrat Jahan",
				timestamp: "45 mins ago",
				note: "Treated 42 pediatric diarrhea patients. Administered IV saline and distributed 1,200 Aquatabs strips.",
			},
		],
		safetyNotes:
			"Maintain strict sterile hand hygiene. Disinfect examination cots regularly.",
	},
	{
		id: "task-bd-3",
		title: "Emergency Sandbag Reinforcement at Fulgazi Sluice Gate",
		description:
			"Stack 5,000 geotextile sandbags along weakened dyke perimeter near Fulgazi market to prevent flood waters from entering Feni city center.",
		category: "sandbagging",
		priority: "high",
		status: "in_progress",
		incidentId: "inc-bd-3",
		incidentTitle:
			"Muhuri & Gumti River Overflow Inundating Residential Sectors",
		assignedTeamId: "team-3",
		assignedTeamName: "Feni Community Sandbagging & Flood Evac Patrol",
		assignedVolunteerIds: ["vol-1"],
		location: {
			address: "Fulgazi Sluice Gate No. 2, Feni",
			lat: 23.132,
			lng: 91.428,
		},
		requiredSkills: ["search_rescue", "evac_transport"],
		volunteersNeeded: 8,
		estimatedDurationHours: 5,
		deadline: "Urgent (ASAP)",
		createdBy: "Kazi Ashraful Islam",
		createdAt: "2 hours ago",
		checkIns: [
			{
				id: "chk-4",
				volunteerId: "vol-1",
				volunteerName: "Kazi Ashraful Islam",
				timestamp: "25 mins ago",
				note: "Placed 1,800 sandbags. Dyke crest raised by 2.5 feet. Water seepage slowing down.",
			},
		],
		safetyNotes: "Beware of fast current near breached embankment sections.",
	},
	{
		id: "task-bd-4",
		title: "Marooned Family Boat Extraction in Sunamganj Haor",
		description:
			"Deploy motorized rescue boats to reach isolated rooftop families in remote haor villages without phone network, ferrying them to designated shelters.",
		category: "search_rescue",
		priority: "critical",
		status: "in_progress",
		incidentId: "inc-bd-1",
		incidentTitle: "Surma River Embankment Breach Submerging Villages",
		assignedTeamId: "team-4",
		assignedTeamName: "BDRCS Haor Water Rescue & Boat Squad",
		assignedVolunteerIds: ["vol-5"],
		location: {
			address: "Bishwamvarpur & Tahirpur Haor, Sunamganj",
			lat: 25.085,
			lng: 91.38,
		},
		requiredSkills: ["search_rescue", "evac_transport"],
		volunteersNeeded: 5,
		estimatedDurationHours: 7,
		deadline: "Nightfall (18:30)",
		createdBy: "Shamim Reza (Water Wing Lead)",
		createdAt: "3 hours ago",
		checkIns: [
			{
				id: "chk-5",
				volunteerId: "vol-5",
				volunteerName: "Shamim Reza",
				timestamp: "1 hour ago",
				note: "Rescued 34 stranded people from 3 submerged schools. Transported to Tahirpur shelter.",
			},
		],
		safetyNotes:
			"Always carry spare outboard motor fuel and emergency searchlights for twilight.",
	},
	{
		id: "task-bd-5",
		title: "Drone Reconnaissance of Jamuna River Bank Erosion",
		description:
			"Fly UAV thermal and high-resolution camera over 6km stretch of Jamuna riverbank at Chilmari to map active erosion lines and pinpoint high-risk homesteads.",
		category: "recon",
		priority: "medium",
		status: "unassigned",
		incidentId: "inc-bd-4",
		incidentTitle: "Catastrophic Jamuna River Bank Erosion Swallowing Farmland",
		assignedVolunteerIds: [],
		location: {
			address: "Chilmari Port Ghat, Kurigram",
			lat: 25.553,
			lng: 89.671,
		},
		requiredSkills: ["drone_recon", "comms_radio"],
		volunteersNeeded: 2,
		estimatedDurationHours: 3,
		deadline: "Tomorrow 10:00 AM",
		createdBy: "Brig. Gen. Tanvir Ahmed (FSCD Command)",
		createdAt: "1 hour ago",
		checkIns: [],
		safetyNotes:
			"Observe Civil Aviation drone flight ceiling and river wind speed limits.",
	},
];

export const ANALYTICS_DATA = {
	hourlyIncidentTrends: [
		{ time: "00:00", reports: 12, resolved: 8, critical: 4 },
		{ time: "03:00", reports: 18, resolved: 11, critical: 6 },
		{ time: "06:00", reports: 34, resolved: 19, critical: 12 },
		{ time: "09:00", reports: 56, resolved: 32, critical: 18 },
		{ time: "12:00", reports: 72, resolved: 48, critical: 24 },
		{ time: "15:00", reports: 65, resolved: 52, critical: 21 },
		{ time: "18:00", reports: 48, resolved: 44, critical: 15 },
		{ time: "21:00", reports: 31, resolved: 28, critical: 9 },
	],
	incidentByType: [
		{ type: "Flood", active: 6, resolved: 4 },
		{ type: "Cyclone", active: 4, resolved: 2 },
		{ type: "Erosion/Slide", active: 3, resolved: 3 },
		{ type: "Waterlogging", active: 2, resolved: 5 },
		{ type: "Hazmat", active: 1, resolved: 2 },
		{ type: "Fire", active: 1, resolved: 4 },
	],
	resourceFulfillmentBySector: [
		{
			sector: "Dhaka Command Sector",
			requested: 120,
			fulfilled: 105,
			rate: 87.5,
		},
		{ sector: "Sylhet Haor Basin", requested: 210, fulfilled: 185, rate: 88.1 },
		{
			sector: "Chattogram Coastal Belt",
			requested: 190,
			fulfilled: 172,
			rate: 90.5,
		},
		{
			sector: "Feni & Muhuri River Zone",
			requested: 145,
			fulfilled: 118,
			rate: 81.4,
		},
		{
			sector: "Kurigram Jamuna Corridor",
			requested: 95,
			fulfilled: 82,
			rate: 86.3,
		},
		{
			sector: "Cox's Bazar Coastal Sector",
			requested: 80,
			fulfilled: 74,
			rate: 92.5,
		},
	],
};
